apiVersion: v1
kind: Service
metadata:
  name: spring-boot-Docker-Kubernetes-service
spec:
  selector:
    app: spring-boot-Docker-Kubernetes-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer