server:
  port: 8080

spring:
  data:
    cassandra:
      contact-points: localhost:9042
      port: 9042
      keyspace-name: demo_keyspace
      local-datacenter: datacenter1
      schema-action: create_if_not_exists
