version: "3.9"

services:
  springboot-app:
    build:
      context: .
      dockerfile: deploy/Dockerfile
    container_name: springboot-deploy
    ports:
      - "7200:7200"
    restart: unless-stopped
    volumes:
      - ./deploy:/app/deploy