api:
  url: "https://jsonplaceholder.typicode.com/posts"


logging:
  level:
    root: INFO
    com.example: DEBUG   # your package logs at DEBUG
    org.springframework.web: WARN
    com.demo: DEBUG
  file:
    path: logs           # base log directory
    name: app.log        # main log file name