spring:
  application:
    name: spring-boot-MCP-Shopping-Cart

  data:
    mongodb:
      uri: mongodb://localhost:27017/cart-db

  ai:
    mcp:
      server:
        type: SYNC
        stdio: true
        name: shopping-cart-server
        version: 1.0.0

  main:
    web-application-type: none
    banner-mode: off

logging:
  pattern:
    console: ""
